# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Results
    url: '/course'
    weight: 20
    identifier: courses
  - name: Our Benchmark
    url: '/course/example/'
    weight: 30
    parent: courses
  - name: Download
    url: '/post'
    weight: 40
  - name: Our Team
    url: '/home/people'
    weight: 50
